### ISSUE TITLE
Triple 非侵入式使用 grpc-go 调研

### ISSUE THREAD

**Issue by FoghostCn** [dubbogo/dev-docs#1]
### 背景
当前侵入grpc的实现方式导致合入官方grpc代码比较困难

### 调研结果
目前结论是非侵入式可以实现目前功能，但直接修改为非侵入式实现改动太大：

1. triple项目大部分需要重写
2. dubbo-go项目也有部分代码直接使用grpc-go
3. proto-gen代码也需要修改

方案调整为分阶段实施：

1. encoding模块迁入triple仓库，删除 `TwoWayCodec` 实现，使用官方codec实现
2. 合入最新release版grpc官方代码，官方仓库 go 最小1.17
3. 为各依赖方提供迁移方案，逐步迁移至非侵入式实现
4. 升级侵入代码，废弃dubbogo-grpc-go仓库，转为依赖官方grpc-go

grpc扩展实现Tri非侵入实现思路：

1. codec 删除 `TwoWayCodec`，这个类的目的是为了编码的时候区分请求和相应，
   1. codec 配置不是pb则将请求体使用 `TripleRequest`包裹，codec时用类型断言做编解码逻辑，类似于 `triple_wrapper.proto`
   2. 接受请求时检查header content-type 如果非pb序列化（或非grpc请求）则使用 `triple_wrapper` 解码，codec时用类型断言类型判断
   3. 判断泛化请求 `TripleRequest.Generic`
2. 非grpc+proto协议/泛化调用， 删除 InvokeWithArgs，修改为每个服务方法单独注册到grpc，采用通用Handler处理，可参考triple-optimize分支
3. proxyMode 理论上可以使用grpc.Server的 `UnknownServiceHandler`实现，参考 [grpc-proxy](https://github.com/mwitkow/grpc-proxy) 
4. 自定义header 和 trailer
   - grpc示例 [https://github.com/grpc/grpc-go/blob/3292193519c3a61e19232348f543a9b318f80d50/examples/features/metadata/server/main.go](https://github.com/grpc/grpc-go/blob/3292193519c3a61e19232348f543a9b318f80d50/examples/features/metadata/server/main.go)
#### 附
* 客户端发送自定义header
```go
// Create and send header.
md := metadata.Pairs("timestamp", time.Now().Format(timestampFormat))
ctx := metadata.NewOutgoingContext(context.Background(), md)
ctx = metadata.AppendToOutgoingContext(context.Background(), "custom", "xxxxxx")
r, err := c.UnaryEcho(ctx, &pb.EchoRequest{Message: message})
```
* 客户端读取服务端返回header 
```go
var header, trailer metadata.MD
r, err := c.UnaryEcho(ctx, &pb.EchoRequest{Message: message}, grpc.Header(&header), grpc.Trailer(&trailer))
```
* interceptor中操作header
```go
md := metadata.Pairs("timestamp", time.Now().Format(timestampFormat))
ctx := metadata.NewOutgoingContext(context.Background(), md)
md, err := metadata.FromIncomingContext(ctx)
md, err := metadata.FromOutgoingContext(ctx)
ctx = metadata.AppendToOutgoingContext(context.Background(), "custom", "xxxxxx")
```
* 服务端自定义header和trailer 
```go
// 读取请求header 
md, ok := metadata.FromIncomingContext(ctx)
// 返回header
grpc.SendHeader(ctx, header)
// 返回trailer 
grpc.SetTrailer(ctx, trailer)
// 获取 stream 
stream := grpc.ServerTransportStreamFromContext(ctx)
```

**Comment by justxuewei** [comment]
@FoghostCn 你没有 push 到 main 分支的权限吗？

EDIT: 我们先在这讨论，回头我 push 一份引用本 issue 的 md 文件就行。

**Comment by justxuewei** [comment]
我看 https://github.com/dubbogo/triple/pull/37 应该基本实现了删除 `TwoWayCodec` 和单独注册的需求，我们可以从中借鉴很多。

另外这种非侵入式使用 grpc-go 我认为基本需要对 triple 进行重构。我建议不要破坏 dubbogo/grpc-go 目前的主分支，在 triple, dubbogo/grpc-go, apache/dubbo-go 下各拉一个 new-triple 分支（如果你觉得 triple-optimize 分支可用的话直接在这个分支上做也可以，我建议是借鉴 triple-optimize 分支但不使用，我们把 Triple 这部分内容重写一份），把目前 grpc-go 最新的分支引入到 dubbogo/grpc-go:triple 分支，这样我们在重构伊始，就是完全机遇纯净的、最新的 grpc-go 代码。

我也会拿出一部分精力来参与 triple 的重构事宜，我觉得既然要搞，就把 triple 设计的更优雅、美观一些，时间上我们不着急，我们后续在定一下整体的计划。

@FoghostCn @Leospard What do you think?

**Comment by FoghostCn** [comment]
OK
